[tox]
envlist =
    py39
    py310
    py311
    py312
    py313
    py314

requires =
    pip<24.1
    virtualenv<20.27

[testenv]
deps =
    # parameterized
    pytest>=7.4.4
    pytest-cov>=4.1.0
    toml;python_version<'3.11'
    pytest-benchmark>=4.0.0
    hypothesis>=6.96.0
    pytest_mock
    pytest-xdist>=3.5.0
commands =
    pytest test -vv --ignore=test/test_perf.py --ignore=test/test_perf_fast.py --cov=bitrab --cov-fail-under=35
    pytest test/test_perf.py test/test_perf_fast.py -vv -p no:xdist --benchmark-only
setenv =
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1